<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Radius_of_Circle_through_three_points</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="NXOpen">
      <HintPath>..\..\..\..\..\..\..\Program Files\Siemens\NX 12.0\NXBIN\managed\NXOpen.dll</HintPath>
    </Reference>
    <Reference Include="NXOpen.Guide">
      <HintPath>..\..\..\..\..\..\..\Program Files\Siemens\NX 12.0\NXBIN\managed\NXOpen.Guide.dll</HintPath>
    </Reference>
    <Reference Include="NXOpen.UF">
      <HintPath>..\..\..\..\..\..\..\Program Files\Siemens\NX 12.0\NXBIN\managed\NXOpen.UF.dll</HintPath>
    </Reference>
    <Reference Include="NXOpen.Utilities">
      <HintPath>..\..\..\..\..\..\..\Program Files\Siemens\NX 12.0\NXBIN\managed\NXOpen.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="NXOpenUI">
      <HintPath>..\..\..\..\..\..\..\Program Files\Siemens\NX 12.0\NXBIN\managed\NXOpenUI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
